import { Component, OnInit } from '@angular/core';
import { Product } from 'src/app/models/product';
import { MessengerService } from 'src/app/services/messenger.service';

@Component({
  selector: 'app-cart',
  templateUrl: './cart.component.html',
  styleUrls: ['./cart.component.css'],
})
export class CartComponent implements OnInit {
  cartItems: any = [
    // { id: 1, productId: 1, productName: 'Test 1', qty: 4, price: 100 },
    // { id: 2, productId: 3, productName: 'Test 3', qty: 5, price: 50 },
    // { id: 3, productId: 2, productName: 'Test 2', qty: 3, price: 150 },
    // { id: 4, productId: 4, productName: 'Test 4', qty: 2, price: 200 },
  ];

  cartTotal = 0;
  constructor(private msg: MessengerService) {}

  ngOnInit(): void {
    //! Subscribe will add an eventListener to the cart component which will continuously listen to the event generated by messenger Service
    this.msg.getmsg().subscribe((product: any) => {
      this.addProductToCart(product);
    });
  }

  addProductToCart(product: Product) {
    let flag = 0;
    if (this.cartItems.length != 0) {
      this.cartItems.forEach((element: any) => {
        // console.log(element.productId == product.id);
        if (element.productId == product.id) {
          element['qty'] = element.qty + 1;
          flag = 1;
        }
      });
    }

    if (flag == 0) {
      this.cartItems.push({
        productId: product.id,
        qty: 1,
        productName: product.name,
        price: product.price,
      });
    }

    console.log(this.cartItems);
    this.cartTotal = 0;
    this.cartItems.forEach((item: any) => {
      this.cartTotal += item.qty * item.price;
    });
  }
}
